server:
  port: 8900
logging:
  file: /java/C2S_LOGS/ums/ums.log
  level:
    gov.samhsa.c2s.ums: info
info:
  component: User Management Service
spring:
  datasource:
    # configure url, username and password per environment
    url: jdbc:mysql://localhost:3306/ums?autoReconnect=true
    username: root
    password: admin
# Override default configurations or Add more configurations for pls API
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: create
c2s:
  ums:
    ssn:
      codeSystem: http://hl7.org/fhir/sid/us-ssn
      codeSystemOID: urn:oid:2.16.840.1.113883.4.1
      displayName: SSN
    gender:
      codeSystem: http://hl7.org/fhir/administrative-gender
      codeSystemOID: urn:oid:2.16.840.1.113883.4.642.1.2
      displayName: GENDER
    mrn:
      codeSystem: https://bhits.github.io/consent2share/
      codeSystemOID: urn:oid:1.3.6.1.4.1.21367.13.20.200
      displayName: MRN
    Pagination:
      defaultSize: 10
      maxSize: 100
