server:
  port: 8900
logging:
  file: /java/C2S_LOGS/ums/ums.log
  level:
    gov.samhsa.c2s.ums: info
info:
  component: User Management Service
spring:
  datasource:
    # configure url, username and password per environment
    url: jdbc:mysql://localhost:3306/ums?autoReconnect=true
    username: root
    password: admin
# Override default configurations or Add more configurations for pls API
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: create
  mail:
  # UMS will use the e-mail server configured in this section to send e-mails
    # Please configure valid e-mail server below to connect to SMTP server
    # Configure host, port, username and password per environment
    host: mail_host
    port: 25
    protocol: smtp
    username: mail_username
    password: mail_password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: mail_host
c2s:
  ums:
    ssn:
      codeSystem: http://hl7.org/fhir/sid/us-ssn
      codeSystemOID: urn:oid:2.16.840.1.113883.4.1
      displayName: SSN
    gender:
      codeSystem: http://hl7.org/fhir/administrative-gender
      codeSystemOID: urn:oid:2.16.840.1.113883.4.642.1.2
      displayName: GENDER
    mrn:
      codeSystem: https://bhits.github.io/consent2share/
      codeSystemOID: urn:oid:1.3.6.1.4.1.21367.13.20.200
      displayName: MRN
    Pagination:
      defaultSize: 10
      maxSize: 100
    scim:
      url: http://localhost:8080/uaa
    email-sender:
      # c2s-ui endpoint
      pp-ui-route: /c2s-ui
      pp-ui-verification-relative-path: "/fe/account/verification"
      pp-ui-verification-email-token-arg-name: "emailToken"
      brand: Consent2Share
      email-token-expiration-in-days: 7
security:
  oauth2:
    client:
      client-id: ums
      client-secret: changeit
      access-token-uri: http://localhost:8080/uaa/oauth/token
  basic:
    enabled: false