server:
  port: 8457
logging:
  file: /java/C2S_LOGS/ums/ums.log
info:
  component: User Management Service
spring:
  datasource:
    # configure url, username and password per environment
    url: jdbc:mysql://localhost:3306/ums?autoReconnect=true
    username: root
    password: admin
  mail:
  # UMS will use the e-mail server configured in this section to send e-mails
    # Please configure valid e-mail server below to connect to SMTP server
    # Configure host, port, username and password per environment
    host: mail_host
    port: 25
    protocol: smtp
    username: mail_username
    password: mail_password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: mail_host
  messages:
    basename: i18n/messages
c2s:
  ums:
    ssn:
      codeSystem: http://hl7.org/fhir/sid/us-ssn
      codeSystemOID: urn:oid:2.16.840.1.113883.4.1
      displayName: SSN
    gender:
      codeSystem: http://hl7.org/fhir/administrative-gender
      codeSystemOID: urn:oid:2.16.840.1.113883.4.642.1.2
      displayName: GENDER
    mrn:
      codeSystem: https://bhits.github.io/consent2share/
      codeSystemOID: urn:oid:1.3.6.1.4.1.21367.13.20.200
      displayName: MRN
      prefix: C2S-DEV
      length: 6
    Pagination:
      defaultSize: 10
      maxSize: 100
    scim:
      url: http://localhost:8080/uaa
    email-sender:
      # c2s-ui endpoint
      c2s-ui-route: /c2s-ui
      c2s-ui-verification-relative-path: "/account/verification"
      c2s-ui-verification-email-token-arg-name: "emailToken"
      brand: Consent2Share
      email-token-expiration-in-days: 7
    fhir:
      publish:
        enable: false
        # configure fhir server base url
        serverUrl: http://fhirtest.uhn.ca/baseDstu3
security:
  oauth2:
    client:
      client-id: ums
      client-secret: changeit
      access-token-uri: http://localhost:8080/uaa/oauth/token
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /ums
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://${C2S_DB_HOST:ums-db.c2s.com}:${C2S_DB_PORT:3306}/ums?autoReconnect=true